# Generated by Django 4.0.1 on 2022-02-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_flight_number_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Airline', to='flights.flight'),
        ),
    ]
