# Generated by Django 4.0.1 on 2022-02-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_airline_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight'),
        ),
    ]
