# Generated by Django 4.0.1 on 2022-02-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airline_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='link',
        ),
    ]
