# Generated by Django 4.0.1 on 2022-02-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_airline_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.flight'),
            preserve_default=False,
        ),
    ]
