# Generated by Django 4.0.1 on 2022-02-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_airline_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='link',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flights.airline'),
            preserve_default=False,
        ),
    ]
