# Generated by Django 4.0.1 on 2022-02-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_multiple_reservations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Multiple_Reservations',
            new_name='Tickets',
        ),
    ]
