# Generated by Django 4.0.1 on 2022-02-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_multiple_reservations_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
